In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as numpy
from sklearn.datasets import load_digits

digits = load_digits()

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [63]:
lr = LogisticRegression(max_iter=200)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9648148148148148

In [64]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9814814814814815

In [65]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [66]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [67]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
	print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [68]:
def get_score(model, X_train, X_test, y_train, y_test):
	model.fit(X_train, y_train)
	return model.score(X_test, y_test)

In [69]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [70]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
	X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
	scores_l.append(get_score(LogisticRegression(max_iter=200), X_train, X_test, y_train, y_test))
	scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
	scores_rf.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, y_train, y_test))

In [71]:
scores_l

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [72]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [73]:
scores_rf

[0.9315525876460768, 0.9515859766277128, 0.9232053422370617]

In [74]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=200), digits.data, digits.target)	# did same thing as above 

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [75]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [76]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93055556, 0.91111111, 0.95543175, 0.9637883 , 0.93036212])